package mockbackend

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"plumb/internal/mockdata"
)

// ontapMux builds the fixed set of ONTAP REST API paths
// internal/netappnative/ontap.go and ontap_countertables.go actually call,
// serving synthetic values instead of a real cluster's. Every path,
// response shape, and unit-conversion direction here is the exact inverse
// of what that collector does to arrive at a display value — see its own
// doc comments for the forward direction of each conversion.
//
// Two counter pairs (node_cpu_busy's raw/base, and each disk's
// busy/denominator) are generated by accumulating two running totals at a
// fixed ratio to each other via counterAccumulator — since
// delta(a)/delta(b) converges to whatever ratio their two accumulation
// rates were set to, this reproduces the intended target percentage
// exactly without needing to simulate ONTAP's actual internal counters.
func ontapMux(arr mockdata.Array) *http.ServeMux {
	mux := http.NewServeMux()
	counters := newCounterAccumulator()

	mux.HandleFunc("GET /api/cluster/metrics", func(w http.ResponseWriter, r *http.Request) {
		// volume_avg_latency: display = latency.total(usec) / 1000.
		// Thresholds (8ms/15ms) are in ms, so emit microseconds.
		ms := arr.CurrentValue("volume_avg_latency", arr.ID+"|volume_avg_latency", "frontend", 8, 15, time.Now())
		writeJSON(w, map[string]any{
			"records": []map[string]any{
				{"latency": map[string]any{"total": ms * 1000}, "timestamp": time.Now().Format("2006-01-02 15:04:05 -0700")},
			},
		})
	})

	mux.HandleFunc("GET /api/cluster/nodes", func(w http.ResponseWriter, r *http.Request) {
		// node_cpu_busy: display = delta(raw)/delta(base)*100.
		pct := arr.CurrentValue("node_cpu_busy", arr.ID+"|node_cpu_busy", "backend", 70, 85, time.Now())
		raw := counters.accumulate(arr.ID+"|cpu_raw", pct)
		base := counters.accumulate(arr.ID+"|cpu_base", 100)
		writeJSON(w, map[string]any{
			"records": []map[string]any{
				{"statistics": map[string]any{"processor_utilization_raw": raw, "processor_utilization_base": base}},
			},
		})
	})

	mux.HandleFunc("GET /api/storage/aggregates", func(w http.ResponseWriter, r *http.Request) {
		// aggr_space_used_percent: display = sum(used)/sum(size)*100 — a
		// direct snapshot, no delta, so this can just fix size and derive
		// used from the target percentage every time.
		pct := arr.CurrentValue("aggr_capacity", arr.ID+"|aggr_capacity", "backend", 80, 90, time.Now())
		const size = 1_000_000.0
		writeJSON(w, map[string]any{
			"records": []map[string]any{
				{"space": map[string]any{"block_storage": map[string]any{"size": size, "used": size * pct / 100}}},
			},
		})
	})

	mux.HandleFunc("GET /api/snapmirror/relationships", func(w http.ResponseWriter, r *http.Request) {
		sec := arr.CurrentValue("snapmirror_lag", arr.ID+"|snapmirror_lag", "backend", 90, 180, time.Now())
		writeJSON(w, map[string]any{
			"records": []map[string]any{
				{"lag_time": formatISODuration(sec)},
			},
		})
	})

	mux.HandleFunc("GET /api/network/ethernet/ports", func(w http.ResponseWriter, r *http.Request) {
		// nic_errors: display = rate(raw)*60, thresholds already errors/min.
		// Band args (0.01, 5) mirror severity_watch/severity_critical in
		// netapp_ontap.yml: any sustained nonzero CRC rate is a fault by
		// industry practice, so "healthy" targets genuine near-zero.
		perMin := arr.CurrentValue("nic_errors", arr.ID+"|nic_errors", "frontend", 0.01, 5, time.Now())
		total := counters.accumulate(arr.ID+"|nic_errors", perMin/60.0)
		half := total / 2
		writeJSON(w, map[string]any{
			"records": []map[string]any{
				{"statistics": map[string]any{"device": map[string]any{
					"receive_raw":  map[string]any{"errors": half},
					"transmit_raw": map[string]any{"errors": total - half},
				}}},
			},
		})
	})

	mux.HandleFunc("GET /api/cluster/counter/tables/disk:constituent", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, map[string]any{
			"name": "disk:constituent",
			"counter_schemas": []map[string]any{
				{"name": "disk_busy_percent", "type": "percent", "denominator": map[string]any{"name": "base_for_disk_busy_percent"}},
				{"name": "base_for_disk_busy_percent", "type": "delta"},
			},
		})
	})

	mux.HandleFunc("GET /api/cluster/counter/tables/disk:constituent/rows", func(w http.ResponseWriter, r *http.Request) {
		// aggr_disk_busy: display = avg over disks of delta(busy)/delta(denom)*100.
		pct := arr.CurrentValue("aggr_disk_busy", arr.ID+"|aggr_disk_busy", "backend", 70, 85, time.Now())
		records := make([]map[string]any, 0, 2)
		for _, disk := range []string{"disk-1", "disk-2"} {
			busy := counters.accumulate(arr.ID+"|"+disk+"|busy", pct)
			denom := counters.accumulate(arr.ID+"|"+disk+"|denom", 100)
			records = append(records, map[string]any{
				"id": disk,
				"counters": []map[string]any{
					{"name": "disk_busy_percent", "value": busy},
					{"name": "base_for_disk_busy_percent", "value": denom},
				},
			})
		}
		writeJSON(w, map[string]any{"records": records})
	})

	mux.HandleFunc("GET /api/cluster/counter/tables/nic_common/rows", func(w http.ResponseWriter, r *http.Request) {
		// nic_util_percent: display = max(rx,tx rate)/link_speed_bytes_per_sec*100.
		// Link fixed at 1000M (125,000,000 B/s); accumulate bytes at the
		// exact rate needed to hit the target percentage of that link.
		pct := arr.CurrentValue("nic_utilization", arr.ID+"|nic_utilization", "frontend", 75, 90, time.Now())
		const linkBytesPerSec = 1000 * 125000.0
		rxRate := linkBytesPerSec * pct / 100
		rx := counters.accumulate(arr.ID+"|nic_rx_bytes", rxRate)
		tx := counters.accumulate(arr.ID+"|nic_tx_bytes", rxRate*0.4) // asymmetric, more realistic than identical rx/tx
		writeJSON(w, map[string]any{
			"records": []map[string]any{
				{
					"id":         "node1:e0a",
					"properties": []map[string]any{{"name": "speed", "value": "1000M"}},
					"counters": []map[string]any{
						{"name": "receive_bytes", "value": rx},
						{"name": "transmit_bytes", "value": tx},
					},
				},
			},
		})
	})

	return mux
}

func formatISODuration(totalSeconds float64) string {
	s := int64(totalSeconds)
	if s < 0 {
		s = 0
	}
	h := s / 3600
	m := (s % 3600) / 60
	sec := s % 60
	return fmt.Sprintf("PT%dH%dM%dS", h, m, sec)
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(v)
}
